### ISSUE TITLE
Async client support

### ISSUE THREAD

**Issue by lmmx** [lmmx/range-streams#26]
This library doesn't support usage of async clients

```py
import httpx
from range_streams import RangeStream, _EXAMPLE_URL

c = httpx.AsyncClient()
s = RangeStream(url=_EXAMPLE_URL, client=c)
```
⇣
```
Traceback (most recent call last):
  File "/home/louis/dev/testing/rangestreams/async/async_rng.py", line 5, in <module>
    s = RangeStream(url=_EXAMPLE_URL, client=c)
  File "/home/louis/dev/range-streams/src/range_streams/stream.py", line 127, in __init__
    self.add(byte_range=byte_range)
  File "/home/louis/dev/range-streams/src/range_streams/stream.py", line 515, in add
    self.send_head_request()
  File "/home/louis/dev/range-streams/src/range_streams/stream.py", line 439, in send_head_request
    resp.raise_for_status()
AttributeError: 'coroutine' object has no attribute 'raise_for_status'
>>> 
sys:1: RuntimeWarning: coroutine 'AsyncClient.send' was never awaited
```

**Comment by lmmx** [comment]
To resolve this initialisation bug, either:

- Rewrite the head request routine as async-friendly
- Add a new attribute `sync_client` which defaults to the client if the client `isinstance(httpx.Client)` else makes a `httpx.Client`

I like the 2nd option

**Comment by lmmx** [comment]
```
import httpx
from range_streams import RangeStream, _EXAMPLE_URL

c = httpx.AsyncClient()
s = RangeStream(url=_EXAMPLE_URL, client=c)
s.add((1,3))
```
⇣
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/louis/dev/range-streams/src/range_streams/stream.py", line 550, in add
    req = self.send_request(byte_range)
  File "/home/louis/dev/range-streams/src/range_streams/stream.py", line 454, in send_request
    return RangeRequest(
  File "/home/louis/dev/range-streams/src/range_streams/request.py", line 33, in __init__
    self.setup_stream()
  File "/home/louis/dev/range-streams/src/range_streams/request.py", line 50, in setup_stream
    self.raise_for_non_partial_content()
  File "/home/louis/dev/range-streams/src/range_streams/request.py", line 57, in raise_for_non_partial_content
    if self.response.status_code != 206:
AttributeError: 'coroutine' object has no attribute 'status_code'
```

**Comment by lmmx** [comment]
Made an attempt and undone it, leaving only the initial outline - needs to be clarified where would I want to `await`, and will the class itself need to be made afresh to handle async client?

**Comment by lmmx** [comment]
This should be made much easier by the introduction of a single stream 'mode' (see #29)

**Comment by lmmx** [comment]
I think it may be desirable to leave the async requesting to the [package-external] fetch function, and just allow the creation (or modification) of a PngStream from the successfully obtained async response (in fact, are responses async?)

**Comment by lmmx** [comment]
A `force_async` flag is a good choice, and retaining the single class (as for HTTPX's `Response` class) is too.

All `httpx.Response` objects have both `iter_bytes` and `aiter_bytes` methods, and incorrect use (sync iterator with async generator/async iterator with sync generator) throws a TypeError, e.g.

```py
>>> async def gimme(stream):                                                                                               
...     async for b in stream:                                                                                             
...             return b                                                                                                   
...  
>>> import httpx                                                                                                           
>>> sync_c = httpx.Client()                                                                                                
>>> sync_req = sync_c.build_request("GET", _EXAMPLE_URL)                                                                   
>>> sync_resp = sync_c.send(sync_req, stream=True)
>>> stream = sync_resp.aiter_bytes()                                                                                       
>>> val = asyncio.run(gimme(stream))                                                                                       
Traceback (most recent call last):                                                                                         
  File "<stdin>", line 1, in <module>                                                                                      
  File "/home/louis/miniconda3/envs/rangestreams/lib/python3.9/asyncio/runners.py", line 44, in run                        
    return loop.run_until_complete(main)                                                                                   
  File "/home/louis/miniconda3/envs/rangestreams/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete    
    return future.result()                                                                                                 
  File "<stdin>", line 2, in gimme                                                                                         
  File "/home/louis/miniconda3/envs/rangestreams/lib/python3.9/site-packages/httpx/_models.py", line 1577, in aiter_bytes  
    async for raw_bytes in self.aiter_raw():                                                                               
  File "/home/louis/miniconda3/envs/rangestreams/lib/python3.9/site-packages/httpx/_models.py", line 1624, in aiter_raw    
    raise RuntimeError("Attempted to call an async iterator on an sync stream.")                                           
RuntimeError: Attempted to call an async iterator on an sync stream.
```

where the async function `gimme` gives the first chunk, which for the example file at `range_streams._EXAMPLE_URL` is the entirety of the file's bytes

**Comment by lmmx** [comment]
The following methods will need to involve an async check:

- `__init__`
- `set_client`
- `register_range`
- `handle_overlap`
- `read`
- `seek`
- `send_request`
- `get_monostream`
- `send_head_request` (but see note below on `sync_client`)
- `add`
- `close`

Additionally, the `sync_client` property will currently create a new synchronous `Client` every time it's called if the stream's client is async. Instead it should set an internal `_sync_client` for use only through this method. (The same doesn't need to be done for async clients. You could also pass one through to be shared across a session but oof that seems messy). Down the line the sync client should be taken out and whatever it was doing should be handled via the async client

**Comment by lmmx** [comment]
Still to do:
- [ ] tests (can reuse the example made while developing it in [this gist](https://gist.github.com/lmmx/e05b7f820a5a44a65c795ddc77911178#file-async_stream_class_rangestream-py))
- [ ] docs (especially the aforementioned need to call `add_async` after initialisation, and the single request mode limit), probably in the module docstring and package docstring

**Comment by lmmx** [comment]
Implemented: 68604a7c271f886b327c8bcd79da3fc3d3590668

- No docs written up yet
- Only tests for the creation and errors, not for checking response content

**Comment by lmmx** [comment]
I wasn't using this:

```py
        if whence == SEEK_END:
            self._load_all()
```

in the `RangeResponse.seek` method, but rather than remove, I'm going to prevent its use on an async stream to keep the seek method synchronous

**Comment by lmmx** [comment]
Closing after #36 completed; remaining to be done in #37
